apibaseurl=http://localhost:4111
apiVersion=/api/v1
adminToken=Basic YWRtaW46YWRtaW4=
maxDeposit=5000

uiRemote=http://192.168.1.149:4444/wd/hub
uiBaseUrl=http://192.168.1.149:3000
uiBrowser=chrome
uiBrowserSize=1920x1080

# Database configuration
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers